name: Update Changelog

on:
  workflow_dispatch:

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure CHANGELOG.md exists
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
          fi

      - name: Set Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Fetch closed PRs since the last tag or commit
        id: pr_details
        run: |
          PR_LIST=$(gh pr list --state closed --base main --json number,title,body --jq '.[] | "\(.number): \(.title) \(.body)"')
          echo "$PR_LIST" > pr_list.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Append PR descriptions to CHANGELOG.md
        run: |
          while read -r pr; do
            PR_NUMBER=$(echo "$pr" | cut -d':' -f1)
            PR_TITLE=$(echo "$pr" | cut -d':' -f2-)
            echo "## [PR #$PR_NUMBER] - $PR_TITLE" >> CHANGELOG.md
          done < pr_list.txt

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub-provided token
