name: Test Workflow

on:
  push:
    branches:
      - doc-updates

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Test echo
      run: echo "Workflow triggered successfully!"
