name: Create PR with Commit Bodies

on:
  push:
    branches:
      - doc-updates

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history to ensure you have the full commit history

    - name: Fetch main branch
      run: git fetch origin main

    - name: Get commit message bodies
      id: get_commit_bodies
      run: |
        commit_bodies=$(git log --format=%B origin/main..HEAD)
        echo "COMMIT_BODIES<<EOF" >> $GITHUB_ENV
        echo "$commit_bodies" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create a pull request
      uses: peter-evans/create-pull-request@v5
     
