name: Update PR with Commit Messages

on:
  push:
    branches:
      - doc-updates

jobs:
  update_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to ensure you have the full commit history

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Get commit message bodies with hashes
        id: get_commit_bodies
        run: |
          commit_bodies=$(git log origin/main..origin/doc-updates --pretty=format:"%h%n%b%n---END---" | awk 'BEGIN { RS="---END---"; FS="\n" }
          {
            hash = $1
            body = substr($0, index($0, "\n") + 1)
            
            # Check if the body is not empty
            if (body !~ /^[[:space:]]*$/) {
              # Replace newlines with <br> or preserve them for multiline
              gsub(/\n/, "<br>", body)
              print hash ": " body "<hr>"
            }
          }')
      
          echo "Commit Bodies with Hashes:"
          echo "$commit_bodies"
      
          # Save the commit bodies with hashes to the environment variable
          echo "COMMIT_BODIES<<EOF" >> $GITHUB_ENV
          echo "$commit_bodies" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Find existing pull request
        id: find_pr
        run: |
          pr=$(gh pr list --head doc-updates --state open --json number --jq '.[0].number')
          echo "PR_NUMBER=$pr" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR description if exists
        if: env.PR_NUMBER != ''
        run: |
          gh pr edit $PR_NUMBER --body "${{ env.COMMIT_BODIES }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a draft pull request if not exists
        if: env.PR_NUMBER == ''
        run: |
          gh pr create --base main --head doc-updates --title "Draft Pull Request from doc-updates" --body "${{ env.COMMIT_BODIES }}" --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
